<%@ Page Title="Countries" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Countries.aspx.cs" Inherits="hrTablesDatabase.Countries" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Countries</h2>
    <p>
        <asp:Label ID="Label1" runat="server" Text="CO"></asp:Label>
&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" Text="COUNTRY_NAME"></asp:Label>
&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="REGION_ID"></asp:Label>
&nbsp;&nbsp;&nbsp;
        <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="COUNTRY_ID" DataSourceID="SqlDataSource1" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
            <Columns>
                <asp:BoundField DataField="COUNTRY_ID" HeaderText="COUNTRY_ID" ReadOnly="True" SortExpression="COUNTRY_ID" />
                <asp:BoundField DataField="COUNTRY_NAME" HeaderText="COUNTRY_NAME" SortExpression="COUNTRY_NAME" />
                <asp:BoundField DataField="REGION_ID" HeaderText="REGION_ID" SortExpression="REGION_ID" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString3 %>" ProviderName="<%$ ConnectionStrings:ConnectionString3.ProviderName %>" SelectCommand="SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID FROM COUNTRIES"></asp:SqlDataSource>
    </p>
    <address>
        &nbsp;</address>
</asp:Content>
